[toolchain]
anchor_version = "0.25.0"

[features]
seeds = false
skip-lint = false
[programs.devnet]
distribution_program = "4tXE3MBtiraiLALMezP1YmMm22QFofDraqzRAeUqB8dx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/takshak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
